### PR TITLE
week 3 post, missing jamies bit and lots of editing. tired. so tired

### PR DESCRIPTION
**Pull request by nicholekitmitto**
@jamieomaguire Add your stuff for this past week. We'll clean this up at tomorrow's meeting.

### CODE REVIEW

**Comment by jamieomaguire** [comment]
@nicholedwight :)

**Comment by nicholekitmitto** [comment]
🐙

**Comment by jamieomaguire** [comment]
@nicholedwight 🍔

**Review by jamieomaguire — APPROVED** [review]
🥇 💩

**Pull request merged**
